### ISSUE TITLE
Google Drive link doesn't include New Horizons music

### ISSUE THREAD

**Issue by Deozaan** [animal-crossing-music-extension/ac-music-extension#137]
The readme has a link to the music used by this extension, which is hosted on a Google Drive link. It seems that even though the extension has been updated to use the music from Animal Crossing New Horizons, the Google Drive link has not been updated.

**Comment by paladique** [comment]
Since 4.0 we've removed any dependency on this folder. It's defunct and no longer used so it will be removed from our documentation soon.

**Comment by Deozaan** [comment]
I thought the point of linking to the Google Drive folder with the music was to maintain the spirit of the open source nature of the extension and provide a link to the source audio files as well.

**Comment by PikaDude** [comment]
The Google Drive link was used for the older versions of the extension. If people downloaded a copy of the extension via GitHub, they also needed to download the required audio so the extension would work, as they were not bundled together. The Google Drive link is simply just there for legacy reasons and serves no purpose since newer versions now remotely stream the audio from an external source.

**Comment by paladique** [comment]
+1 and to add on to the open source part here - the music _technically_ isn't ours. With that said it's probably wise to not keep a public link to this lying around.

**Comment by Deozaan** [comment]
Thanks for clarifying that for me.
