### ISSUE TITLE
Chrome can't download the extension?

### ISSUE THREAD

**Issue by Naturally-Delicious** [animal-crossing-music-extension/ac-music-extension#24]
It's just stuck on "checking". It still downloads, but it stops at 400mb~ and then crashes, then tells me to restart Chrome. Any fix?

**Comment by JdotCarver** [comment]
Long story short not really..
Explanation : Chrome hates long downloads and that's the main problem of the extension having every file localized makes it huge.
You could manually install it, though Chrome wouldn't be able to validate it to the store and you'd be stuck with a workaround far from a permanent solution.

Monday, 21 August 2017, 00:28AM +02:00 from Naturally-Delicious notifications@github.com<mailto:notifications@github.com>:


It's just stuck on "checking". It still downloads, but it stops at 400mb~ and then crashes, then tells me to restart Chrome. Any fix?

**Comment by Naturally-Delicious** [comment]
Yeah I figured it didn't download because of the huge file size. I kept trying to download it after a few fails and it magically downloaded fully and now I have the extension!

**Comment by JdotCarver** [comment]
Ah ! I'm so glad to hear that, there really wasn't much I could do so good thing it sorted itself out !

Monday, 21 August 2017, 11:12PM +02:00 from Naturally-Delicious notifications@github.com<mailto:notifications@github.com>:


Yeah I figured it didn't download because of the huge file size. I kept trying to download it after a few fails and it magically downloaded fully and now I have the extension!

**Comment by paladique** [comment]
This issue has been resolved. Closing! ✨
