### ISSUE TITLE
Are you still here ? (I need help)

### ISSUE THREAD

**Issue by thefrenchfangirl** [animal-crossing-music-extension/ac-music-extension#29]
When I upload your new version on google extensions I'm facing an issue.
Moreover I'm a total beginner ....
Here is the problem : 
Failed to load ressource: net: :ERR_FILE_NOT_FOUND     11am.ogg.1
Uncaught (in promise) DOMException     _generated_background_page.html1

**Comment by JdotCarver** [comment]
Hey theFrenchFangirl,
I have to admit I was more project coordinator on this one. I had more passion than knowledge! 😄 That's why if anyone's reading this and you think you can do it, please go ahead I'm sure you'll delight all the AC fans.

Now that's out of the way, have you checked if your download was complete? Cause at first glance it seems you're missing one of the game's files. 
Si j'étais toi j'aurais commencé par justement chercher si il manque vraiment ce "11am.ogg" dans les fichiers de l'extension. As-tu téléchargé les fichiers audio ? Le lien Google Drive est dans la description. Tu met tout les dossiers téléchargés avec les autres dossiers de l'extension.

**Comment by thefrenchfangirl** [comment]
Hey JdotCarver!
I have finally made it! And I have added the wild world raining option too :) 
How can I give you the modified files? So everyone could have access to it.

And I have another question each time that I open google now it asks me if I'm really sure to enable developer extensions and I have to close the popup each time if I want my other extensions to appear... So I wanted to upload it on chrome store that way I could delete the files on my computer and also it would stop asking me to enable the AC extension or not, but it asks me to pay 5$. So my question is can you update the version pleaase? (that way I could share it with my friends more easily ^^).

(And your French is very good!)

**Comment by JdotCarver** [comment]
Yep. That's... Google for you. Chrome used to let you have any personal extension and do your thing but they changed their policy and private extensions from developper mode trigger this message because they want you do do something about it. 

But did you change the code then? You meant you implemented the changes and all? If so I'll update the contributors list and I'll wrap up and update the extension! :) 

Yes, je suis français (plot twist).

**Comment by thefrenchfangirl** [comment]
AH! 
Bon je vais écrire en français alors ... ^^
Du coup oui je suis sur google Chrome. 
Et j'ai juste changé  l'icone sur la barre d'outil et rajouté les musiques d'ACWW quand il pleut (c'est tout). Comme je le disais je ne connais rien à rien au codage donc je ferais tache au milieu de véritables gens qui s'y connaissent même un peu. Mais du coup si on peut upgrade la version ça serait super biiieen ! 

Et meilleur plot twist de l'univers haha !

**Comment by JdotCarver** [comment]
Et donc voilà. Tu met le doigt sur le problème. 
Moi non plus !
J'ai merge les commits et j'ai fait quelques tweaks mais le gros du travail vient vraiment des codeurs. Et vu que c'est sur la base du volontariat, si personne n'a l'envie d'aider, le projet reste en limbo. C'est une des choses que j'espérait contrecarrer avec Github. Toute personne est libre de prendre notre travail et de le continuer.

Si jamais ça n'arrive pas, quand j'aurais plus de moyens j'engagerais un codeur pour fignoler l'extension. Je dois t'avouer que ça me met physiquement mal à l'aise quand je dois penser à ce projet que je n'ai pas pu terminer! ^^'

**Comment by thefrenchfangirl** [comment]
Du coup on fait pour que je te donne les fichiers bidouillés ? (Parce que je n'ai pas gardé de trace des lignes que j'ai rajouté) pour que tu puisses mettre à jour l'extension sur le chrome store et autre ?
C'est une très bonne idée, mais d'ici là j'espère qu'on aura tous fait un travail correct...

**Comment by thefrenchfangirl** [comment]
Bonsoir, 
J'ai tout mis sur ce google drive : https://drive.google.com/open?id=1HH52P6pttgZM4cv3u-KimTq57o9SvrAH
Comme ça si tu veux mettre ton add on a jour avec les modifications eh bien feel free :)

**Comment by JdotCarver** [comment]
Merci thefrenchfangirl,
Dès que j'ai les fonds nécessaires je paye quelqu'un pour tout merge. C'est pas l'envie qui manque en ce moment mais vraiment le temps. Ça devrait arriver en Mars si tout va bien. Encore merci pour ton aide, c'est les personnes comme toi qui me donnent espoir. :)

**Comment by Syzztem** [comment]
Salut, je suis un ami a TheFrenchFanGirl et je suis ok pour faire le merge

**Comment by JdotCarver** [comment]
Ok, est-ce qu'on peut parler de ça en privé alors @Syzztem ?

**Comment by Syzztem** [comment]
@JdotCarver 
oui bien sur t'as Discord?

**Comment by JdotCarver** [comment]
@Syzztem 
Yes IDLT#9162

**Comment by Syzztem** [comment]
J'ai créé le pull request et fait le merge t'as plus qu'a accepter

**Comment by Syzztem** [comment]
Tu devrais créer une release pour montrer que le projet est fini aussi

**Comment by paladique** [comment]
Looks like this has been merged and resolved, so closing this issue. A new version is currently under development in [this repo](https://github.com/PikaDude/ac-music-extension-revived).
