### ISSUE TITLE
Email still being monitored? 

### ISSUE THREAD

**Issue by paladique** [animal-crossing-music-extension/ac-music-extension#33]
👋 Hi! Is AnimalCrossingMusicExtension@gmail.com still another way to reach you? Sent an email there earlier today, so just making sure you're still monitoring it.

**Comment by JdotCarver** [comment]
No, it isn't really. Sorry! I'm going to look into that!

Wednesday, 29 May 2019, 08:58PM +02:00 from Jasmine Greenaway notifications@github.com<mailto:notifications@github.com>:


👋 Hi! Is AnimalCrossingMusicExtension@gmail.com<mailto:AnimalCrossingMusicExtension@gmail.com> still another way to reach you? Sent an email there earlier today, so just making sure you're still monitoring it.

**Comment by paladique** [comment]
Ok, no worries. I'll just explain what I sent: I'm a longtime fan of the extension and also a developer, so I wanted to know if you're still looking for a maintainer to help out! Let me know, because I'd love to help keep this going.

**Comment by JdotCarver** [comment]
Yeah totally ! I’m working on making a business out of social media and it’s very time consuming. Every time I look at the extension it just depresses me because I have neither the time nor the expertise to give it what it deserves. I feel that with the new animal crossing coming out on Switch it would be a waste of a good opportunity for it to be the same as always. So yeah. I’m most definitely interested since in the other mail you sent, you seemed way more apt than I am at handling this. Haha. 😊

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Jasmine Greenaway <notifications@github.com>
Envoyé : Friday, May 31, 2019 6:45:57 PM
À : JdotCarver/Animal-Crossing-Music-Extension
Cc : JdotCarver; Comment
Objet : Re: [JdotCarver/Animal-Crossing-Music-Extension] Email still being monitored? (#33)


Ok, no worries. I'll just explain what I sent: I'm a longtime fan of the extension and also a developer, so I wanted to know if you're still looking for a maintainer to help out! Let me know, because I'd love to help keep this going.

**Comment by paladique** [comment]
Totally understand! I've been looking for a project to be part of so super happy to get started! How did you want to proceed? Here's some options:

- You could add me as a collaborator to this repo 
- Create an organization, transfer this repo to the org and add me and yourself as an owner
- I make a fork and make a new app in the store (preferably would avoid!)

No matter which option, it would prob be best to [add me as a publisher](https://developer.chrome.com/webstore/publish#set-up-group-publishing) instead of making a new app in the extension store.

Very much happy to help you walk through these options if you need help or advice via chat/video/etc.

**Comment by JdotCarver** [comment]
OK great info.
I'll add you as a Publisher and create an Organization this weekend then!

**Comment by JdotCarver** [comment]
Ok! It's done! This took way too long but its finally done!
You have been invited to the Google Publisher Group and the Github Organization. Where both the Extension and the Repo now reside in. 
Thanks for being so patient. :/

**Comment by paladique** [comment]
No problem, totally understand! Thank you :)

**Comment by paladique** [comment]
@JdotCarver so the last thing I don't have is write access, which will be important for me to merge Pull Requests and manage Issues.  So in order for me to do this, you can either [elevate my Role to Owner](url), or [give me Admin permission level (in organization settings)](https://help.github.com/en/articles/repository-permission-levels-for-an-organization). I think once that's all set I should be good to go!

**Comment by paladique** [comment]
Thank you! I am good on access now!
