### ISSUE TITLE
Add K.K. songs in their Club LOL variants if possible

### ISSUE THREAD

**Issue by Mimimax** [animal-crossing-music-extension/ac-music-extension#59]
And have the option to play either DJ or 8bit versions, for either weekdays and sundays, or saturdays, or both.

**Comment by PikaDude** [comment]
I don't believe anyone has dumped these versions of the songs anywhere, so it would be very difficult.

**Comment by Mimimax** [comment]
Oh I see. Is there anyway they can be ripped?

**Comment by PikaDude** [comment]
I don't believe dumping would be possible or easy. I think someone would need to manually record the audio of every song in-game.

**Comment by PikaDude** [comment]
Closing this due to the unlikelihood of this feature ever coming to fruition due to the difficulties of ripping K.K. Slider's music from the game as the format appears to be quite difficult to dump, read and convert. If anyone is able to easily convert the required tracks into a more common format (preferably ogg vorbis) then we can re-open this issue.
