### ISSUE TITLE
Town tune still plays when paused due to tab audio

### ISSUE THREAD

**Issue by PikaDude** [animal-crossing-music-extension/ac-music-extension#90]

**Comment by Julian-MM** [comment]
Areas of code responsible for playing town tunes at the hour are:
AudioManager.js -> line 43 (part of AudioManager.playHourlyMusic method)
StateManager.js -> line 162 (part of timeKeeper.registerHourlyCallback method)

I'm leaning towards thinking it may be caused by AudioManager.playHourlyMusic(), which plays the town tune when called, as long as the town tune is enabled in the options, and isHourChange is true. It's called by events "hourMusic", "gameChange" and "weatherChange".
